/**
 * Against Malaria Foundation (AMF) Cost-Effectiveness Model
 *
 * Based on GiveWell's November 2025 CEA spreadsheet:
 * https://docs.google.com/spreadsheets/d/1VEtie59TgRvZSEVjfG7qcKBKcQyJn8zO91Lau9YNqXc
 *
 * This model calculates the cost-effectiveness of AMF's insecticide-treated
 * net (ITN) distribution program in terms of multiples of GiveWell's benchmark
 * (unconditional cash transfers).
 */

/**
 * GiveWell's benchmark value: the value generated by $1 of unconditional
 * cash transfers. All cost-effectiveness estimates are expressed as multiples
 * of this benchmark.
 *
 * Source: GiveWell's moral weights and discount rate spreadsheet
 * Value: 0.00333 UoV per $1
 */
export const BENCHMARK_VALUE_PER_DOLLAR = 0.00333;

export interface AMFInputs {
  /** Grant size in USD */
  grantSize: number;

  /** Cost to reach one person under age 5 with ITNs (USD) */
  costPerUnder5Reached: number;

  /** Years of effective coverage provided by distributed nets */
  yearsEffectiveCoverage: number;

  /** Malaria-attributable mortality rate among people under 5 (proportion) */
  malariaMortalityRate: number;

  /** Effect of ITN distributions on deaths related to malaria (proportion reduction) */
  itnEffectOnDeaths: number;

  /** Moral weight assigned to averting one under-5 death (in units of value) */
  moralWeightUnder5: number;

  /** Adjustment for mortality benefits to people age 5+ (proportion of under-5 value) */
  adjustmentOlderMortalities: number;

  /** Moral weight for averting death of person age 5+ (for cost per life calculation) */
  moralWeight5Plus: number;

  /** Adjustment for developmental benefits - long-term income increases (proportion) */
  adjustmentDevelopmental: number;

  /** Adjustment for additional program benefits/downsides (proportion) */
  adjustmentProgramBenefits: number;

  /** Adjustment for grantee-level factors (proportion) */
  adjustmentGrantee: number;

  /** Adjustment for leverage effects (proportion) */
  adjustmentLeverage: number;

  /** Adjustment for funging - displacement of other funding (proportion) */
  adjustmentFunging: number;

  /** Combined leverage/funging adjustment for cost per life calculation (from Main CEA row 216) */
  adjustmentLeverageFungingForCostPerLife: number;
}

export interface AMFResults {
  /** Number of people under 5 reached with ITNs */
  peopleUnder5Reached: number;

  /** Number of deaths averted among people under 5 */
  deathsAvertedUnder5: number;

  /** Cost per under-5 death averted (USD) */
  costPerUnder5DeathAverted: number;

  /** Initial cost-effectiveness in multiples of benchmark (before adjustments) */
  initialXBenchmark: number;

  /** Final cost-effectiveness in multiples of benchmark (after all adjustments) */
  finalXBenchmark: number;

  /** Final cost per life saved in USD (after all adjustments) */
  finalCostPerLifeSaved: number;
}

/**
 * Calculate AMF cost-effectiveness using GiveWell's methodology
 *
 * Calculation flow:
 * 1. People reached = grant size / cost per person
 * 2. Deaths averted = people × coverage years × mortality rate × ITN effect
 * 3. Initial CE = (deaths averted × moral weight) / (grant size × benchmark)
 * 4. Multiply by (1 + adjustment factors) for final CE
 */
export function calculateAMF(inputs: AMFInputs): AMFResults {
  const {
    grantSize,
    costPerUnder5Reached,
    yearsEffectiveCoverage,
    malariaMortalityRate,
    itnEffectOnDeaths,
    moralWeightUnder5,
    adjustmentOlderMortalities,
    moralWeight5Plus,
    adjustmentDevelopmental,
    adjustmentProgramBenefits,
    adjustmentGrantee,
    adjustmentLeverage,
    adjustmentFunging,
    adjustmentLeverageFungingForCostPerLife,
  } = inputs;

  // Step 1: Calculate people reached
  const peopleUnder5Reached = grantSize / costPerUnder5Reached;

  // Step 2: Calculate deaths averted among under-5s
  // Deaths averted = people × years of coverage × mortality rate × intervention effect
  const deathsAvertedUnder5 =
    peopleUnder5Reached *
    yearsEffectiveCoverage *
    malariaMortalityRate *
    itnEffectOnDeaths;

  // Step 3: Calculate cost per death averted
  const costPerUnder5DeathAverted = grantSize / deathsAvertedUnder5;

  // Step 4: Calculate initial cost-effectiveness in terms of benchmark
  // Value generated = deaths averted × moral weight
  // CE multiple = value generated / (grant size × benchmark value per dollar)
  const valueGenerated = deathsAvertedUnder5 * moralWeightUnder5;
  const benchmarkValue = grantSize * BENCHMARK_VALUE_PER_DOLLAR;
  const initialXBenchmark = valueGenerated / benchmarkValue;

  // Step 5: Apply adjustments for other benefits
  // These are applied sequentially:
  // 1. Add 5+ mortality benefits: multiply by (1 + older adjustment)
  // 2. Add developmental benefits: multiply by (1 + developmental adjustment)
  const ceWithOlder = initialXBenchmark * (1 + adjustmentOlderMortalities);
  const ceWithAllBenefits = ceWithOlder * (1 + adjustmentDevelopmental);

  // Step 6: Apply additional adjustments multiplicatively
  // Each adjustment is applied as a (1 + adj) factor
  const finalXBenchmark =
    ceWithAllBenefits *
    (1 + adjustmentProgramBenefits) *
    (1 + adjustmentGrantee) *
    (1 + adjustmentLeverage + adjustmentFunging);

  // Step 7: Calculate final cost per life saved
  // Formula from GiveWell spreadsheet:
  // cost_per_life = cost_per_u5_death × (u5_deaths / total_deaths) / (1 + leverage_funging_adj)
  //
  // The adjustmentOlderMortalities is the ratio of 5+ VALUE to u5 VALUE:
  //   adjustment = (5+_deaths × 5+_weight) / (u5_deaths × u5_weight)
  //
  // To get the deaths ratio: 5+_deaths / u5_deaths = adjustment × (u5_weight / 5+_weight)
  const deathsRatio5PlusToUnder5 =
    adjustmentOlderMortalities * (moralWeightUnder5 / moralWeight5Plus);
  const fractionUnder5 = 1 / (1 + deathsRatio5PlusToUnder5);
  const finalCostPerLifeSaved =
    costPerUnder5DeathAverted *
    fractionUnder5 /
    (1 + adjustmentLeverageFungingForCostPerLife);

  return {
    peopleUnder5Reached,
    deathsAvertedUnder5,
    costPerUnder5DeathAverted,
    initialXBenchmark,
    finalXBenchmark,
    finalCostPerLifeSaved,
  };
}
