/**
 * Deworming (Evidence Action / Deworm the World) Cost-Effectiveness Model
 *
 * Based on GiveWell's Deworming CEA spreadsheet:
 * Source: data/givewell-spreadsheets/deworming.xlsx
 *
 * This model calculates the cost-effectiveness of Evidence Action's Deworm the World
 * program in terms of multiples of GiveWell's benchmark (unconditional cash transfers).
 *
 * The model is based on:
 * - Long-term income effects from Miguel & Kremer (2004) and follow-up studies
 * - Country/region-specific worm burden adjustments
 * - Charity-level adjustments (wastage, monitoring, fungibility)
 * - Intervention-level adjustments (health effects, spillovers, etc.)
 * - Leverage and funging adjustments
 */

/**
 * GiveWell's benchmark value: the value generated by $1 of unconditional
 * cash transfers. All cost-effectiveness estimates are expressed as multiples
 * of this benchmark.
 *
 * Calculated from the deworming spreadsheet: ~0.00335 UoV per $1
 */
export const BENCHMARK_VALUE_PER_DOLLAR = 0.00335453394;

export interface DewormingEvidenceActionInputs {
  /** Grant size in USD */
  grantSize: number;

  /** Cost per child dewormed per year (USD) - includes all costs from all funders */
  costPerChildPerYear: number;

  /**
   * Percentage of total program costs covered by Deworm the World.
   * Used to calculate total spending from all contributors.
   * E.g., 0.608 means DtW covers 60.8% of costs
   */
  percentageCostsDtW: number;

  /**
   * Worm burden adjustment - ratio of worm burden in target population
   * to the study population (Miguel & Kremer 2004).
   * This adjusts the treatment effect based on local infection prevalence.
   */
  wormBurdenAdjustment: number;

  /**
   * Present value of lifetime benefits from a year of deworming,
   * in terms of increases in ln(consumption).
   * This is calculated from:
   * - Base treatment effect (0.109 ln income from Miguel & Kremer)
   * - Replicability adjustment (0.13)
   * - Years of treatment adjustment (0.9)
   * - Discount rate and benefit duration (40 years)
   * - Decay adjustment (-0.1)
   * - Household resource sharing multiplier (2.0)
   * - Worm burden adjustment (location-specific)
   */
  pvBenefitsLnConsumption: number;

  /**
   * Value assigned to increasing ln(consumption) by one unit for one person
   * for one year (in units of value).
   * From GiveWell's moral weights: ~1.44 UoV
   */
  valueLnConsumptionUnit: number;

  /**
   * Charity-level adjustment factor accounting for:
   * - Risk of wastage (ineffective goods, etc.)
   * - Quality of monitoring and evaluation
   * - Confidence in funds being used for intended purpose
   * Typically ~0.91 (9% reduction)
   */
  charityAdjustmentFactor: number;

  /**
   * Intervention-level adjustment factor accounting for:
   * - Direct health effects
   * - HIV reduction benefits
   * - Diseases of affluence (potential harms)
   * - Averted mortality
   * - Short-term anemia effects
   * - Investment of income increases
   * - Non-income long-run benefits
   * - Drug resistance
   * - Unprogrammed deworming
   * - Marginal funding priority
   * - General equilibrium effects
   * Typically ~1.073 (7.3% increase)
   */
  interventionAdjustmentFactor: number;

  /**
   * Percent change in cost-effectiveness from leverage and funging.
   * Leverage: our funding causes others to spend more
   * Funging: our funding displaces other funding
   * Typically between -0.05 and +0.26
   */
  leverageFungingPercentChange: number;
}

export interface DewormingEvidenceActionResults {
  /** Number of children dewormed per year */
  childrenDewormedPerYear: number;

  /** Units of value from each year of deworming (per child) */
  unitsValuePerYearDeworming: number;

  /** Total units of value generated (initial, before adjustments) */
  totalUnitsValueInitial: number;

  /** Units of value generated per dollar spent (initial) */
  unitsValuePerDollarInitial: number;

  /** Initial cost-effectiveness in multiples of benchmark */
  initialXBenchmark: number;

  /** Cost-effectiveness after charity-level adjustments */
  xBenchmarkAfterCharityAdj: number;

  /** Cost-effectiveness after intervention-level adjustments */
  xBenchmarkAfterInterventionAdj: number;

  /** Final cost-effectiveness after all adjustments including leverage/funging */
  finalXBenchmark: number;
}

/**
 * Calculate Deworming (Evidence Action) cost-effectiveness using GiveWell's methodology
 *
 * Calculation flow:
 * 1. Total spending = grant size / percentage covered by DtW
 * 2. Children dewormed = total spending / cost per child per year
 * 3. Units of value per child-year = PV benefits (ln consumption) × value per ln unit
 * 4. Total units of value = children × units of value per child-year
 * 5. Initial CE = (units of value / grant size) / benchmark
 * 6. Apply charity-level adjustments (wastage, monitoring, fungibility)
 * 7. Apply intervention-level adjustments (health effects, spillovers, etc.)
 * 8. Apply leverage/funging adjustments
 */
export function calculateDewormingEvidenceAction(
  inputs: DewormingEvidenceActionInputs
): DewormingEvidenceActionResults {
  const {
    grantSize,
    costPerChildPerYear,
    percentageCostsDtW,
    pvBenefitsLnConsumption,
    valueLnConsumptionUnit,
    charityAdjustmentFactor,
    interventionAdjustmentFactor,
    leverageFungingPercentChange,
  } = inputs;

  // Step 1: Calculate total spending by all contributors
  // Our grant leverages additional funding from governments, other donors, etc.
  const totalSpendingAllContributors = grantSize / percentageCostsDtW;

  // Step 2: Calculate children dewormed per year
  // Uses total spending from all contributors
  const childrenDewormedPerYear = totalSpendingAllContributors / costPerChildPerYear;

  // Step 3: Calculate units of value from each year of deworming
  // PV benefits is already adjusted for worm burden in the input parameter
  const unitsValuePerYearDeworming =
    pvBenefitsLnConsumption * valueLnConsumptionUnit;

  // Step 4: Calculate total units of value generated (initial)
  const totalUnitsValueInitial =
    childrenDewormedPerYear * unitsValuePerYearDeworming;

  // Step 5: Calculate units of value per dollar spent
  // Note: This is based on TOTAL spending, not just our grant
  // This measures the cost-effectiveness of the program itself
  const unitsValuePerDollarInitial = totalUnitsValueInitial / totalSpendingAllContributors;

  // Step 6: Calculate initial cost-effectiveness in multiples of benchmark
  const initialXBenchmark =
    unitsValuePerDollarInitial / BENCHMARK_VALUE_PER_DOLLAR;

  // Step 7: Apply charity-level adjustments
  // These account for wastage, monitoring quality, and fungibility
  const xBenchmarkAfterCharityAdj = initialXBenchmark * charityAdjustmentFactor;

  // Step 8: Apply intervention-level adjustments
  // These account for additional benefits and potential harms
  const xBenchmarkAfterInterventionAdj =
    xBenchmarkAfterCharityAdj * interventionAdjustmentFactor;

  // Step 9: Apply leverage and funging adjustments
  // Leverage increases CE (our funding causes others to spend more)
  // Funging decreases CE (our funding displaces other funding)
  const finalXBenchmark =
    xBenchmarkAfterInterventionAdj * (1 + leverageFungingPercentChange);

  return {
    childrenDewormedPerYear,
    unitsValuePerYearDeworming,
    totalUnitsValueInitial,
    unitsValuePerDollarInitial,
    initialXBenchmark,
    xBenchmarkAfterCharityAdj,
    xBenchmarkAfterInterventionAdj,
    finalXBenchmark,
  };
}
