/**
 * GiveDirectly Cost-Effectiveness Model
 *
 * Based on GiveWell's November 2024 re-evaluation:
 * https://blog.givewell.org/2024/11/12/re-evaluating-the-impact-of-unconditional-cash-transfers/
 * https://docs.google.com/spreadsheets/d/1LqkkwWCud9qGjSJmw9re6DIm5ocpPOaqOJ-KIEVLppk
 *
 * This model calculates the cost-effectiveness of GiveDirectly's unconditional
 * cash transfer program, including consumption benefits, economic spillovers,
 * and mortality reduction effects.
 */

/**
 * GiveWell's benchmark value: the value generated by $1 of consumption doubling
 * at the $2.15/day poverty line.
 * Value: ~0.003 UoV per $1
 */
export const BENCHMARK_VALUE_PER_DOLLAR = 0.003;

export interface GiveDirectlyInputs {
  /** Grant size in USD */
  grantSize: number;

  /** Transfer amount per household (USD) */
  transferAmount: number;

  /** Overhead rate (proportion of transfer, e.g., 0.20 = 20%) */
  overheadRate: number;

  /** Baseline annual consumption of recipients (PPP 2017 USD) */
  baselineConsumption: number;

  /** Years over which consumption benefits persist */
  consumptionPersistenceYears: number;

  /** Discount rate for future consumption (annual) */
  discountRate: number;

  /** Spillover multiplier - additional economic activity per $1 transferred */
  spilloverMultiplier: number;

  /** Discount applied to spillover estimate due to uncertainty */
  spilloverDiscount: number;

  /** Mortality reduction effect (proportion, e.g., 0.23 = 23% reduction) */
  mortalityEffect: number;

  /** Under-5 mortality rate in target population */
  under5MortalityRate: number;

  /** Average household size */
  householdSize: number;

  /** Proportion of household that is under 5 */
  proportionUnder5: number;

  /** Moral weight for averting under-5 death */
  moralWeightUnder5: number;

  /** Discount applied to mortality estimate due to uncertainty */
  mortalityDiscount: number;
}

export interface GiveDirectlyResults {
  /** Number of households reached */
  householdsReached: number;

  /** Total people reached */
  peopleReached: number;

  /** Cost per household (including overhead) */
  costPerHousehold: number;

  /** Present value of consumption benefits per household */
  consumptionBenefitPerHousehold: number;

  /** Spillover benefits per household */
  spilloverBenefitPerHousehold: number;

  /** Deaths averted (under 5) */
  deathsAvertedUnder5: number;

  /** Value from consumption (in UoV) */
  valueFromConsumption: number;

  /** Value from spillovers (in UoV) */
  valueFromSpillovers: number;

  /** Value from mortality reduction (in UoV) */
  valueFromMortality: number;

  /** Total value generated (in UoV) */
  totalValue: number;

  /** Cost-effectiveness in multiples of benchmark */
  xBenchmark: number;
}

/**
 * Calculate GiveDirectly cost-effectiveness
 */
export function calculateGiveDirectly(inputs: GiveDirectlyInputs): GiveDirectlyResults {
  // Cost per household including overhead
  const costPerHousehold = inputs.transferAmount * (1 + inputs.overheadRate);

  // Number of households reached
  const householdsReached = inputs.grantSize / costPerHousehold;
  const peopleReached = householdsReached * inputs.householdSize;

  // Calculate present value of consumption benefits
  // Using log utility: value = ln(consumption_after / consumption_before)
  // Consumption increase from transfer spread over persistence years
  const annualConsumptionIncrease = inputs.transferAmount / inputs.consumptionPersistenceYears;

  // Present value of consumption benefits (discounted)
  let consumptionBenefitPerHousehold = 0;
  for (let year = 0; year < inputs.consumptionPersistenceYears; year++) {
    const discountFactor = Math.pow(1 + inputs.discountRate, -year);
    // Log utility: ln((base + increase) / base) per person per year
    const utilityGain = Math.log(
      (inputs.baselineConsumption + annualConsumptionIncrease) / inputs.baselineConsumption
    );
    consumptionBenefitPerHousehold += utilityGain * inputs.householdSize * discountFactor;
  }

  // Spillover benefits (discounted for uncertainty)
  // Spillover multiplier means $1 generates $(multiplier) in local economic activity
  // We credit the additional activity beyond the direct transfer
  const spilloverBenefitPerHousehold =
    consumptionBenefitPerHousehold *
    (inputs.spilloverMultiplier - 1) *
    (1 - inputs.spilloverDiscount);

  // Mortality reduction benefits
  // Under-5 population in households reached
  const under5Population = peopleReached * inputs.proportionUnder5;

  // Deaths averted = population × mortality rate × mortality effect × discount
  const deathsAvertedUnder5 =
    under5Population *
    inputs.under5MortalityRate *
    inputs.mortalityEffect *
    (1 - inputs.mortalityDiscount);

  // Value calculations (in units of value)
  // Consumption value: benefits per household × households
  // Scale to match benchmark (consumption doubling = 1 UoV)
  const valueFromConsumption = consumptionBenefitPerHousehold * householdsReached;

  const valueFromSpillovers = spilloverBenefitPerHousehold * householdsReached;

  const valueFromMortality = deathsAvertedUnder5 * inputs.moralWeightUnder5;

  const totalValue = valueFromConsumption + valueFromSpillovers + valueFromMortality;

  // Cost-effectiveness as multiple of benchmark
  const xBenchmark = totalValue / (inputs.grantSize * BENCHMARK_VALUE_PER_DOLLAR);

  return {
    householdsReached,
    peopleReached,
    costPerHousehold,
    consumptionBenefitPerHousehold,
    spilloverBenefitPerHousehold,
    deathsAvertedUnder5,
    valueFromConsumption,
    valueFromSpillovers,
    valueFromMortality,
    totalValue,
    xBenchmark,
  };
}
