/**
 * Helen Keller International - Vitamin A Supplementation (VAS) Cost-Effectiveness Model
 *
 * Based on GiveWell's November 2025 CEA spreadsheet:
 * https://docs.google.com/spreadsheets/d/1L6D1mf8AMKoUHrN0gBGiJjtstic4RvqLZCxXZ99kdnA
 *
 * This model calculates the cost-effectiveness of Helen Keller's VAS program
 * in terms of multiples of GiveWell's benchmark (unconditional cash transfers).
 */

/**
 * GiveWell's benchmark value: the value generated by $1 of unconditional
 * cash transfers.
 *
 * Note: Helen Keller spreadsheet uses 0.003355.
 */
export const BENCHMARK_VALUE_PER_DOLLAR = 0.003355;

export interface HelenKellerInputs {
  /** Grant size in USD */
  grantSize: number;

  /** Cost to reach one person under age 5 with VAS (USD) */
  costPerPersonUnder5: number;

  /** Proportion of reached children who would not otherwise receive VAS (counterfactual) */
  proportionReachedCounterfactual: number;

  /** Mortality rate among people under 5 (proportion) */
  mortalityRateUnder5: number;

  /** Effect of VAS on under-five mortality (proportion reduction) */
  vasEffect: number;

  /** Moral weight assigned to averting one under-5 death (in units of value) */
  moralWeightUnder5: number;

  /** Adjustment for developmental benefits - long-term income increases (proportion) */
  adjustmentDevelopmental: number;

  /** Adjustment for additional program benefits/downsides (proportion) */
  adjustmentProgramBenefits: number;

  /** Adjustment for grantee-level factors (proportion) */
  adjustmentGrantee: number;

  /** Adjustment for leverage effects (proportion) */
  adjustmentLeverage: number;

  /** Adjustment for funging - displacement of other funding (proportion) */
  adjustmentFunging: number;
}

export interface HelenKellerResults {
  /** Number of people under 5 reached with VAS */
  peopleUnder5Reached: number;

  /** Number of additional children receiving VAS (after counterfactual adjustment) */
  additionalChildrenCovered: number;

  /** Number of deaths averted among people under 5 */
  deathsAvertedUnder5: number;

  /** Cost per under-5 death averted (USD) */
  costPerDeathAverted: number;

  /** Initial cost-effectiveness in multiples of benchmark (before adjustments) */
  initialXBenchmark: number;

  /** Final cost-effectiveness in multiples of benchmark (after all adjustments) */
  finalXBenchmark: number;

  /** Final cost per life saved in USD (after all adjustments) */
  finalCostPerLifeSaved: number;
}

/**
 * Calculate Helen Keller VAS cost-effectiveness using GiveWell's methodology
 *
 * Calculation flow:
 * 1. People reached = grant size / cost per person
 * 2. Additional children = people × (1 - counterfactual proportion)
 * 3. Deaths averted = additional children × mortality rate × VAS effect
 * 4. Initial CE = (deaths averted × moral weight) / (grant size × benchmark)
 * 5. Apply adjustments for final CE
 */
export function calculateHelenKeller(
  inputs: HelenKellerInputs
): HelenKellerResults {
  const {
    grantSize,
    costPerPersonUnder5,
    proportionReachedCounterfactual,
    mortalityRateUnder5,
    vasEffect,
    moralWeightUnder5,
    adjustmentDevelopmental,
    adjustmentProgramBenefits,
    adjustmentGrantee,
    adjustmentLeverage,
    adjustmentFunging,
  } = inputs;

  // Step 1: Calculate people reached
  const peopleUnder5Reached = grantSize / costPerPersonUnder5;

  // Step 2: Calculate additional children covered (accounting for counterfactual)
  const additionalChildrenCovered =
    peopleUnder5Reached * (1 - proportionReachedCounterfactual);

  // Step 3: Calculate deaths averted among under-5s
  const deathsAvertedUnder5 =
    additionalChildrenCovered * mortalityRateUnder5 * vasEffect;

  // Step 4: Calculate cost per death averted
  const costPerDeathAverted = grantSize / deathsAvertedUnder5;

  // Step 5: Calculate initial cost-effectiveness in terms of benchmark
  const valueGenerated = deathsAvertedUnder5 * moralWeightUnder5;
  const benchmarkValue = grantSize * BENCHMARK_VALUE_PER_DOLLAR;
  const initialXBenchmark = valueGenerated / benchmarkValue;

  // Step 6: Apply adjustments
  // Helen Keller has no older mortalities adjustment (VAS mainly affects under-5s)
  // CE × (1 + developmental) × (1 + program) × (1 + grantee) × (1 + leverage + funging)
  const ceWithDevelopmental = initialXBenchmark * (1 + adjustmentDevelopmental);
  const ceWithProgram = ceWithDevelopmental * (1 + adjustmentProgramBenefits);
  const ceWithGrantee = ceWithProgram * (1 + adjustmentGrantee);
  const finalXBenchmark =
    ceWithGrantee * (1 + adjustmentLeverage + adjustmentFunging);

  // Step 7: Calculate final cost per life saved
  // For VAS, the adjustment factor is (1 + leverage + funging)
  // Cost per life = cost per death / developmental adjustment factor / other adjustments
  const finalCostPerLifeSaved =
    costPerDeathAverted /
    (1 + adjustmentDevelopmental) /
    (1 + adjustmentProgramBenefits) /
    (1 + adjustmentGrantee) /
    (1 + adjustmentLeverage + adjustmentFunging);

  return {
    peopleUnder5Reached,
    additionalChildrenCovered,
    deathsAvertedUnder5,
    costPerDeathAverted,
    initialXBenchmark,
    finalXBenchmark,
    finalCostPerLifeSaved,
  };
}
