/**
 * Malaria Consortium - Seasonal Malaria Chemoprevention (SMC) Cost-Effectiveness Model
 *
 * Based on GiveWell's November 2025 CEA spreadsheet:
 * https://docs.google.com/spreadsheets/d/1De3ZnT2Co5ts6Ccm9guWl8Ew31grzrZZwGfPtp-_t50
 *
 * This model calculates the cost-effectiveness of Malaria Consortium's SMC program
 * in terms of multiples of GiveWell's benchmark (unconditional cash transfers).
 */

/**
 * GiveWell's benchmark value: the value generated by $1 of unconditional
 * cash transfers. All cost-effectiveness estimates are expressed as multiples
 * of this benchmark.
 *
 * Note: Malaria Consortium spreadsheet uses 0.003355, which differs from
 * AMF (0.00333). This may reflect different update cycles for the spreadsheets.
 */
export const BENCHMARK_VALUE_PER_DOLLAR = 0.003355;

export interface MalariaConsortiumInputs {
  /** Grant size in USD */
  grantSize: number;

  /** Cost to reach one child with SMC (USD) */
  costPerChildReached: number;

  /** Malaria-attributable mortality rate among children under 5 (proportion) */
  malariaMortalityRate: number;

  /** Proportion of malaria mortality that occurs during SMC season (proportion) */
  proportionMortalityDuringSeason: number;

  /** Effect of SMC on under-five deaths (proportion reduction) */
  smcEffect: number;

  /** Moral weight assigned to averting one under-5 death (in units of value) */
  moralWeightUnder5: number;

  /** Adjustment for mortality benefits to people age 5+ (proportion of under-5 value) */
  adjustmentOlderMortalities: number;

  /** Adjustment for developmental benefits - long-term income increases (proportion) */
  adjustmentDevelopmental: number;

  /** Adjustment for additional program benefits/downsides (proportion) */
  adjustmentProgramBenefits: number;

  /** Adjustment for grantee-level factors (proportion) */
  adjustmentGrantee: number;

  /** Adjustment for leverage effects (proportion) */
  adjustmentLeverage: number;

  /** Adjustment for funging - displacement of other funding (proportion) */
  adjustmentFunging: number;
}

export interface MalariaConsortiumResults {
  /** Number of children reached with SMC */
  childrenReached: number;

  /** Number of deaths averted among people under 5 */
  deathsAvertedUnder5: number;

  /** Cost per under-5 death averted (USD) */
  costPerDeathAverted: number;

  /** Initial cost-effectiveness in multiples of benchmark (before adjustments) */
  initialXBenchmark: number;

  /** Final cost-effectiveness in multiples of benchmark (after all adjustments) */
  finalXBenchmark: number;
}

/**
 * Calculate Malaria Consortium SMC cost-effectiveness using GiveWell's methodology
 *
 * Calculation flow:
 * 1. Children reached = grant size / cost per child
 * 2. Deaths averted = children × mortality rate × season proportion × SMC effect
 * 3. Initial CE = (deaths averted × moral weight) / (grant size × benchmark)
 * 4. Apply adjustments for final CE
 */
export function calculateMalariaConsortium(
  inputs: MalariaConsortiumInputs
): MalariaConsortiumResults {
  const {
    grantSize,
    costPerChildReached,
    malariaMortalityRate,
    proportionMortalityDuringSeason,
    smcEffect,
    moralWeightUnder5,
    adjustmentOlderMortalities,
    adjustmentDevelopmental,
    adjustmentProgramBenefits,
    adjustmentGrantee,
    adjustmentLeverage,
    adjustmentFunging,
  } = inputs;

  // Step 1: Calculate children reached
  const childrenReached = grantSize / costPerChildReached;

  // Step 2: Calculate deaths averted among under-5s
  // Deaths averted = children × mortality rate × season proportion × SMC effect
  const deathsAvertedUnder5 =
    childrenReached *
    malariaMortalityRate *
    proportionMortalityDuringSeason *
    smcEffect;

  // Step 3: Calculate cost per death averted
  const costPerDeathAverted = grantSize / deathsAvertedUnder5;

  // Step 4: Calculate initial cost-effectiveness in terms of benchmark
  const valueGenerated = deathsAvertedUnder5 * moralWeightUnder5;
  const benchmarkValue = grantSize * BENCHMARK_VALUE_PER_DOLLAR;
  const initialXBenchmark = valueGenerated / benchmarkValue;

  // Step 5: Apply adjustments
  // From the spreadsheet, adjustments are applied as:
  // CE × (1 + older) × (1 + developmental) × (1 + program) × (1 + grantee) × (1 + leverage + funging)
  const ceWithOlder = initialXBenchmark * (1 + adjustmentOlderMortalities);
  const ceWithDevelopmental = ceWithOlder * (1 + adjustmentDevelopmental);
  const ceWithProgram = ceWithDevelopmental * (1 + adjustmentProgramBenefits);
  const ceWithGrantee = ceWithProgram * (1 + adjustmentGrantee);
  const finalXBenchmark =
    ceWithGrantee * (1 + adjustmentLeverage + adjustmentFunging);

  return {
    childrenReached,
    deathsAvertedUnder5,
    costPerDeathAverted,
    initialXBenchmark,
    finalXBenchmark,
  };
}
