/**
 * New Incentives - Conditional Cash Transfers for Vaccination Cost-Effectiveness Model
 *
 * Based on GiveWell's November 2025 CEA spreadsheet:
 * https://docs.google.com/spreadsheets/d/1mTKQuZRyVMie-K_KUppeCq7eBbXX15Of3jV7uo3z-PM
 *
 * This model calculates the cost-effectiveness of New Incentives' vaccination
 * incentive program in terms of multiples of GiveWell's benchmark.
 */

/**
 * GiveWell's benchmark value: the value generated by $1 of unconditional
 * cash transfers.
 *
 * Note: New Incentives spreadsheet uses 0.00333 (same as AMF).
 */
export const BENCHMARK_VALUE_PER_DOLLAR = 0.00333;

export interface NewIncentivesInputs {
  /** Grant size in USD */
  grantSize: number;

  /** Cost to reach one child with vaccination incentive (USD) */
  costPerChildReached: number;

  /** Proportion of reached children who would have been vaccinated anyway (counterfactual) */
  proportionReachedCounterfactual: number;

  /** Probability that an unvaccinated child dies before age 5 (proportion) */
  probabilityDeathUnvaccinated: number;

  /** Effect of vaccination on under-five mortality (proportion reduction) */
  vaccineEffect: number;

  /** Moral weight assigned to averting one under-5 death (in units of value) */
  moralWeightUnder5: number;

  /** Adjustment for mortality benefits to people age 5+ (proportion of under-5 value) */
  adjustmentOlderMortalities: number;

  /** Adjustment for developmental benefits - long-term income increases (proportion) */
  adjustmentDevelopmental: number;

  /** Adjustment for consumption benefits from cash transfers (proportion) */
  adjustmentConsumption: number;

  /** Adjustment for additional program benefits/downsides (proportion) */
  adjustmentProgramBenefits: number;

  /** Adjustment for grantee-level factors (proportion) */
  adjustmentGrantee: number;

  /** Adjustment for leverage effects (proportion) */
  adjustmentLeverage: number;

  /** Adjustment for funging - displacement of other funding (proportion) */
  adjustmentFunging: number;
}

export interface NewIncentivesResults {
  /** Number of children reached with vaccination incentive */
  childrenReached: number;

  /** Number of additional children vaccinated (after counterfactual adjustment) */
  additionalChildrenVaccinated: number;

  /** Number of deaths averted among people under 5 */
  deathsAvertedUnder5: number;

  /** Cost per under-5 death averted (USD) */
  costPerDeathAverted: number;

  /** Initial cost-effectiveness in multiples of benchmark (before adjustments) */
  initialXBenchmark: number;

  /** Final cost-effectiveness in multiples of benchmark (after all adjustments) */
  finalXBenchmark: number;

  /** Final cost per life saved in USD (after all adjustments) */
  finalCostPerLifeSaved: number;
}

/**
 * Calculate New Incentives cost-effectiveness using GiveWell's methodology
 *
 * Calculation flow:
 * 1. Children reached = grant size / cost per child
 * 2. Additional children vaccinated = children × (1 - counterfactual)
 * 3. Deaths averted = additional children × death probability × vaccine effect
 * 4. Initial CE = (deaths averted × moral weight) / (grant size × benchmark)
 * 5. Apply adjustments for final CE
 */
export function calculateNewIncentives(
  inputs: NewIncentivesInputs
): NewIncentivesResults {
  const {
    grantSize,
    costPerChildReached,
    proportionReachedCounterfactual,
    probabilityDeathUnvaccinated,
    vaccineEffect,
    moralWeightUnder5,
    adjustmentOlderMortalities,
    adjustmentDevelopmental,
    adjustmentConsumption,
    adjustmentProgramBenefits,
    adjustmentGrantee,
    adjustmentLeverage,
    adjustmentFunging,
  } = inputs;

  // Step 1: Calculate children reached
  const childrenReached = grantSize / costPerChildReached;

  // Step 2: Calculate additional children vaccinated (accounting for counterfactual)
  const additionalChildrenVaccinated =
    childrenReached * (1 - proportionReachedCounterfactual);

  // Step 3: Calculate deaths averted among under-5s
  const deathsAvertedUnder5 =
    additionalChildrenVaccinated * probabilityDeathUnvaccinated * vaccineEffect;

  // Step 4: Calculate cost per death averted
  const costPerDeathAverted = grantSize / deathsAvertedUnder5;

  // Step 5: Calculate initial cost-effectiveness in terms of benchmark
  const valueGenerated = deathsAvertedUnder5 * moralWeightUnder5;
  const benchmarkValue = grantSize * BENCHMARK_VALUE_PER_DOLLAR;
  const initialXBenchmark = valueGenerated / benchmarkValue;

  // Step 6: Apply adjustments
  // New Incentives has unique adjustments including consumption benefits
  // CE × (1 + older) × (1 + developmental) × (1 + consumption) × (1 + program) × (1 + grantee) × (1 + leverage + funging)
  const ceWithOlder = initialXBenchmark * (1 + adjustmentOlderMortalities);
  const ceWithDevelopmental = ceWithOlder * (1 + adjustmentDevelopmental);
  const ceWithConsumption = ceWithDevelopmental * (1 + adjustmentConsumption);
  const ceWithProgram = ceWithConsumption * (1 + adjustmentProgramBenefits);
  const ceWithGrantee = ceWithProgram * (1 + adjustmentGrantee);
  const finalXBenchmark =
    ceWithGrantee * (1 + adjustmentLeverage + adjustmentFunging);

  // Step 7: Calculate final cost per life saved
  // Inverse of the CE adjustments applied to cost per death
  const finalCostPerLifeSaved =
    costPerDeathAverted /
    (1 + adjustmentOlderMortalities) /
    (1 + adjustmentDevelopmental) /
    (1 + adjustmentConsumption) /
    (1 + adjustmentProgramBenefits) /
    (1 + adjustmentGrantee) /
    (1 + adjustmentLeverage + adjustmentFunging);

  return {
    childrenReached,
    additionalChildrenVaccinated,
    deathsAvertedUnder5,
    costPerDeathAverted,
    initialXBenchmark,
    finalXBenchmark,
    finalCostPerLifeSaved,
  };
}
